# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Stacked
subtitle: To learn is eternity
author: Gabriel Majivu
language: en
timezone: Africa/Nairobi

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://gabeno.github.io
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  style: tomorrow
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 6
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 6
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: vexo

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/gabeno/gabeno.github.io.git
  branch: master
  message: "Updated at {{ now('YYYY-MM-DD HH:mm:ss')  }}"

# Links
twitter_username: https://twitter.com/GabrielMajivu
github_username: gabeno

## ======================== ##
#
#
#author: Gabriel Majivu # 作者
#description: yanm1ng's blog
keyword: blog, writing, article, programming, life, learning, study, project
favicon: css/images/logo.png

excerpt_link: Read more

menu:
 Home: /
 #About: /about/
 Projects: /projects/
 #Tags: /tags/
 Archives: /archives/

# catalog
catalog: false

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment or uyan

comment: false

# gitment config
gitment_owner:
gitment_repo:
gitment_oauth_id:
gitment_oauth_secret:

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id:
ba_track_id:

about:
  banner: /css/images/kilimanjaro.jpg
  avatar: https://avatars1.githubusercontent.com/u/1006432?v=4?v=3&s=460
  description: Take a peek into my world via my musings here.
  # Links
  weibo_username:
  twitter_username: GabrielMajivu
  github_username: gabeno
  zhihu_username:
  douban_username:
